import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import yaml from 'js-yaml';
import { getChecker } from './checkers.js';
import { sendDiscordNotification } from './notify.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const CONFIG_PATH = resolve(ROOT, 'minimaid.config.yml');
const HISTORY_PATH = resolve(ROOT, 'data', 'history.json');

async function main() {
  console.log('[Minimaid] Worker gestartet –', new Date().toISOString());

  const config = yaml.load(readFileSync(CONFIG_PATH, 'utf-8'));
  const timeout = config.settings?.check_timeout || 10000;
  const maxDays = config.settings?.history_max_days || 90;

  const history = loadHistory();
  const now = new Date().toISOString();

  for (const service of config.services) {
    const checker = getChecker(service.type);
    if (!checker) {
      console.warn(`[Minimaid] Unbekannter Service-Typ: ${service.type} (${service.name})`);
      continue;
    }

    console.log(`[Minimaid] Prüfe ${service.name} (${service.type})...`);
    const result = await checker(service, timeout);
    console.log(`  → ${result.status} (${result.responseTime}ms)`);

    if (!history.services[service.id]) {
      history.services[service.id] = { checks: [] };
    }

    const serviceHistory = history.services[service.id];
    const prevCheck = serviceHistory.checks[serviceHistory.checks.length - 1];
    const prevStatus = prevCheck?.status;

    serviceHistory.checks.push({
      timestamp: now,
      status: result.status,
      responseTime: result.responseTime,
      details: result.details || {},
    });

    if (prevStatus && prevStatus !== result.status) {
      console.log(`  ⚡ Statuswechsel: ${prevStatus} → ${result.status}`);
      await sendDiscordNotification(config, service, prevStatus, result.status, result);

      if (!history.incidents) history.incidents = [];
      history.incidents.push({
        id: `inc-${Date.now()}`,
        serviceId: service.id,
        serviceName: service.name,
        title: result.status === 'offline'
          ? `${service.name} ist offline`
          : `${service.name} ist wieder online`,
        status: result.status === 'offline' ? 'investigating' : 'resolved',
        oldStatus: prevStatus,
        newStatus: result.status,
        timestamp: now,
        autoGenerated: true,
      });
    }
  }

  pruneHistory(history, maxDays);
  history.lastUpdated = now;

  writeFileSync(HISTORY_PATH, JSON.stringify(history, null, 2), 'utf-8');
  console.log(`[Minimaid] History gespeichert → ${HISTORY_PATH}`);
  console.log('[Minimaid] Worker beendet.');
}

function loadHistory() {
  if (existsSync(HISTORY_PATH)) {
    try {
      return JSON.parse(readFileSync(HISTORY_PATH, 'utf-8'));
    } catch {
      console.warn('[Minimaid] History-Datei beschädigt, starte neu.');
    }
  }
  return { services: {}, incidents: [], lastUpdated: null };
}

function pruneHistory(history, maxDays) {
  const cutoff = new Date();
  cutoff.setDate(cutoff.getDate() - maxDays);
  const cutoffISO = cutoff.toISOString();

  for (const svcId of Object.keys(history.services)) {
    history.services[svcId].checks = history.services[svcId].checks.filter(
      (c) => c.timestamp >= cutoffISO
    );
  }

  if (history.incidents) {
    history.incidents = history.incidents.filter((i) => i.timestamp >= cutoffISO);
  }
}

main().catch((err) => {
  console.error('[Minimaid] Fataler Fehler:', err);
  process.exit(1);
});
